org: groupcounseling
app: groupcounseling-app
service: GroupCounseling-app

plugins:
  - serverless-offline

custom:
  stage: dev
  serverless-offline:
    httpPort: 3000
    stageVariables:
      foo: "bar"

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  - ${file(./resource-functions/api-sample.yml)}
  - ${file(./resource-functions/api-sample-2.yml)}
  - ${file(./resource-functions/user.yml)}
  - ${file(./resource-functions/debug.yml)}
  - ${file(./resource-functions/communicate.yml)}
  - ${file(./resource-functions/analysis.yml)}
