org: groupcounseling
app: groupcounseling-app
service: GroupCounseling-app

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  - ${file(./resource-functions/api-sample.yml)}
  - ${file(./resource-functions/api-sample-2.yml)}
  - ${file(./resource-functions/user.yml)}
  - ${file(./resource-functions/debug.yml)}
